// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6pt8zaA5UQEHaFQn8nplT9ys8LzCYkOQ',
    appId: '1:631505859970:web:197d3e9e01e5a5ccb04b9b',
    messagingSenderId: '631505859970',
    projectId: 'new-nike-ui-setup',
    authDomain: 'new-nike-ui-setup.firebaseapp.com',
    storageBucket: 'new-nike-ui-setup.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuyBUqVYZI1h3_4LjQGeZa1YeyxVaEpqc',
    appId: '1:631505859970:android:fa8970145256db11b04b9b',
    messagingSenderId: '631505859970',
    projectId: 'new-nike-ui-setup',
    storageBucket: 'new-nike-ui-setup.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYinBtWtFNkug9scFeSgarxTSaDbaRXO8',
    appId: '1:631505859970:ios:0c18c51532ff40e6b04b9b',
    messagingSenderId: '631505859970',
    projectId: 'new-nike-ui-setup',
    storageBucket: 'new-nike-ui-setup.appspot.com',
    iosBundleId: 'com.example.newNike',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYinBtWtFNkug9scFeSgarxTSaDbaRXO8',
    appId: '1:631505859970:ios:0c18c51532ff40e6b04b9b',
    messagingSenderId: '631505859970',
    projectId: 'new-nike-ui-setup',
    storageBucket: 'new-nike-ui-setup.appspot.com',
    iosBundleId: 'com.example.newNike',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6pt8zaA5UQEHaFQn8nplT9ys8LzCYkOQ',
    appId: '1:631505859970:web:2562c3c4a99eb14ab04b9b',
    messagingSenderId: '631505859970',
    projectId: 'new-nike-ui-setup',
    authDomain: 'new-nike-ui-setup.firebaseapp.com',
    storageBucket: 'new-nike-ui-setup.appspot.com',
  );
}
